### ISSUE TITLE
Compose Specificationの訳について

### ISSUE THREAD

**Issue by flyingbarbarian** [matsuand/docs.docker.jp.onthefly#11]
日本語訳をアップロードして頂き有難う御座います。
いつも非常に助けられています。

ところで、『Compose Specification』の訳が『Compose 仕様』なのは分かりにくいかと思います。
というのは、[Compose Specification](https://www.compose-spec.io/)はComposeの特定の仕様を表す固有名詞だからです。

『Docker Compose』を『Docker 構成』と訳さないように、『Compose Specification』もそのままでは良いのではないでしょうか？

**Comment by matsuand** [comment]
ご指摘ありがとうございます。ご指摘内容は熟考致しますが、今のところ否定的です。
固有名詞かどうかで、各単語を訳出する／しないという基準は理解します。Docker Compose を Docker 構成？としない理由は、固有名詞だから、というただそれだけの理由ではありません。製品（商品）名だからです。公式サイドにより公式な訳語が提供されていない限り、勝手に訳してしまうと、対象物を同一とするかどうか、確定できなくなる可能性があり、読者を惑わすことすらあるためです。
一方、まず「Compose SpecificationはComposeの特定の仕様を表す固有名詞」というご説明ですが、"特定の仕様を表す" という言葉の意味が不明です。何かまわりくどく表現なさっていますが、もっと平明に「Compose Specification は Compose の仕様のこと」です。固有名詞という点は同意します。Compose の仕様を表現した、この世で唯一無二のドキュメントのことで、リンクづけもして頂いた先に、そのドキュメントがあります。固有名詞にこだわるなら Compose Specification でも良いかもしれません。ただし specification という単語を見て、日本語読者のすべてが「仕様」のことであると即認識するかどうかは不安です。「仕様」と訳せばその不安はなくなります。私はこの考えを採りたいと思います。
なお、Compose Specification に対してリンクづけして頂いた先は、実質 https://github.com/compose-spec/compose-spec/blob/master/spec.md を指しています。そこをつぶさに読むと、タイトルこそ Compose Specification としていながら、本文中は、例外なく Compose specification (小文字のs) として表記しています。ここから類推されるのは、大文字 S を用いた表記はタイトル向けとして、キャメルケース表記（各単語の先頭文字を大文字化する表記）に過ぎないのではないか、ということです。小文字の s が正しい表記であるとすると、これは「仕様」という一般名詞扱いにすることが、むしろ妥当すると考えます。

**Comment by flyingbarbarian** [comment]
ご説明頂いたことに納得致しました。
確かに、 https://github.com/compose-spec/compose-spec/blob/master/spec.md の本文中で、Compose specification (小文字のs) と表記されていますね。
そして、小文字のsで始まるspecificationを「仕様」と訳すのは、合点がいきます。

思慮が足らずに申し訳ないです。
ご対応頂き有難う御座いました。
