### ISSUE TITLE
404 at /docs.docker.jp.onthefly/language/python/develop/develop-images/build_enhancements.md

### ISSUE THREAD

**Issue by whuang12345** [matsuand/docs.docker.jp.onthefly#12]
リンク切れを発見しました: https://matsuand.github.io/docs.docker.jp.onthefly/language/python/develop/develop-images/build_enhancements.md
当ページは以下から参照しました: https://matsuand.github.io/docs.docker.jp.onthefly/language/python/build-images/

**Comment by matsuand** [comment]
1. アクセスして頂いたURLのトップページに記載しているように、当サイトは2022/04/27を最後にメンテナンスしていません。
2. 最新の日本語訳は、別途 https://matsuand.github.io/docker.docs-ja/ というURLで鋭意提供中です。
3. 当該指摘箇所は、最新ドキュメントにおいて存在しません。

以上により本 issue は無効となりクローズさせていただきます。
