### ISSUE TITLE
CPUリソースの指定

### ISSUE THREAD

**Issue by Crux-One** [matsuand/docs.docker.jp.onthefly#14]
File: [cloud/ecs-compose-features.ch](https://matsuand.github.io/docs.docker.jp.onthefly/cloud/ecs-compose-features/#container-resources)

`cpu` は `cpus` 、値は文字列で指定する仕様に変更になっているようです。

```diff
services:
    nginx:
        image: mycompany/webapp
        deploy:
          resources:
            limits:
-              cpu: 0.5
+              cpus: '0.5'
              memory: 2Gb
```

**Comment by matsuand** [comment]
オリジナルにて当該箇所は削除されました： https://github.com/docker/docs/commit/9949bc70f

よって issue クローズします。

なお本リポジトリおよび提供ドキュメントは 2022/04/27 を最後にメンテナンスしていません。新たな日本語訳は https://matsuand.github.io/docker.docs-ja/ より提供しています。
