### ISSUE TITLE
Docker ACI integration の記述が、実際の動作と異なる

### ISSUE THREAD

**Issue by Gucchiy** [matsuand/docs.docker.jp.onthefly#15]
File: [cloud/aci-integration.ch](https://matsuand.github.io/docs.docker.jp.onthefly/cloud/aci-integration/)

本ページにおける、 docker login azure において、--client-id xx --client-secret yy --tenant-id zz のオプションは現在利用できないようなのですが、どうでしょうか。利用すると、unknown flag: --client-secret などと出力されます。

また、docker context create aci についても、下記 help にある通り、aci コマンドがないように見えます。

> docker context aci --help

Usage:  docker context COMMAND

Manage contexts

Commands:
  create      Create a context
  export      Export a context to a tar archive FILE or a tar stream on STDOUT.
  import      Import a context from a tar or zip file
  inspect     Display detailed information on one or more contexts
  ls          List contexts
  rm          Remove one or more contexts
  show        Print the name of the current context
  update      Update a context
  use         Set the current docker context

CLI において仕様変更があったのでしょうか。

Docker Desktop をインストールし、vesrsion は下記通りです。
Client:
 Version:           27.2.0
 API version:       1.46 (downgraded from 1.47)
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.33.1 (161083)
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by matsuand** [comment]
返信すべきポイントがいくつかあります
1. アクセスして頂いたURLのトップページに記載しているように、当サイトは2022/04/27を最後にメンテナンスしていません。訳出内容はその日付時点のものに過ぎません ＝＞ 情報が古くなり、ご指摘のような情報の齟齬が発生しています
2. 正確なところは公式の（英語の）ドキュメントを参照してください
3. ちなみに日本語訳は、別途 https://matsuand.github.io/docker.docs-ja/ というURLで、鋭意提供中です
4. ACI integration については、まず少なくとも当方は操作経験がありません。また ACI integration は廃止されている様子です。詳細は承知していません。
5. 現状公式ドキュメント https://docs.docker.com/cloud/ にて、廃止されたことが説明されていると同時に、[Compose CLI repository](https://github.com/docker/compose-cli/tree/main/docs) にて関係するドキュメントが参照できるとのことですので、参照してください

ご確認いただけたら issue を閉じてください。

**Comment by Gucchiy** [comment]
ご連絡ありがとうございます、承知しました。
